# Generated by Django 3.2 on 2021-04-14 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_snippet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='snippet',
        ),
    ]
